### model
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora

### dataset
dataset: ours
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/FTmodel
logging_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 15
gradient_accumulation_steps: 2
learning_rate: 5.0e-5  
num_train_epochs: 10.0

### eval
val_size: 0.2
per_device_eval_batch_size: 10
eval_strategy: steps  
eval_steps: 100
warmup_steps: 20

report_to: wandb
run_name: FT

max_samples: 181877
plot_loss: true
fp16: true 
